### ISSUE TITLE
Error finding workout steps: ("'ConcreteStep' object has no attribute 'power_range'",)

### ISSUE THREAD

**Issue by waynedvernon** [gazpachoking/trainaspower#15]
Many thanks for your work.

I have been using Trainaspower without issue until a recent repitition run did not pull through to final surge.  I have pasted the debug log file entry:

Many thanks
```
------------------------------------
2021-07-20 06:00:17.437 | DEBUG    | __main__:main:99 - Error
Traceback (most recent call last):

  File "trainaspower\trainasone.py", line 73, in get_workout

  File "trainaspower\trainasone.py", line 90, in convert_steps

  File "trainaspower\trainasone.py", line 158, in convert_steps

AttributeError: 'ConcreteStep' object has no attribute 'power_range'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "trainaspower\trainasone.py", line 49, in get_next_workouts

  File "trainaspower\trainasone.py", line 76, in get_workout

trainaspower.trainasone.FindWorkoutException: Error finding workout steps: ("'ConcreteStep' object has no attribute 'power_range'",)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "trainaspower\main.py", line 107, in <module>

> File "trainaspower\main.py", line 87, in main

  File "trainaspower\trainasone.py", line 54, in get_next_workouts

trainaspower.trainasone.FindWorkoutException: Error finding next TaO workout: Error finding workout steps: ("'ConcreteStep' object has no attribute 'power_range'",)
2021-07-20 06:00:17.443 | ERROR    | __main__:main:100 - Could not load next Train as One workout. Created taocalendar.html for debugging.
```

**Comment by waynedvernon** [comment]
I have had the same issue again this morning

This was the next scheduled repetition session.

any ideas?

**Comment by gazpachoking** [comment]
Hmm. I'll try to have a look at this. Can you post what one of the problematic workouts looks like on trainasone?

**Comment by waynedvernon** [comment]
![0122C413-0E37-41D8-AC67-20F6B7F5B79F](https://user-images.githubusercontent.com/87783320/127171845-3f6e018a-28b8-4b5f-ad42-45b092fe08db.jpeg)

**Comment by gazpachoking** [comment]
Hmm. It doesn't put a range for the speed? Do your other runs put a range? My workouts come out like this, with the range in the square brackets (`[]`).
![image](https://user-images.githubusercontent.com/187133/127173383-41d5be88-bc1f-4f6e-ba46-7a0288842cc6.png)

**Comment by gazpachoking** [comment]
Aha, do you have this option turned on? That's a requirement right now. I'll add it to the readme.
![image](https://user-images.githubusercontent.com/187133/127180609-2d3e23c8-93fa-4bca-a180-03041090f616.png)

**Comment by gazpachoking** [comment]
New handling should solve this.
