### ISSUE TITLE
Error finding workout steps

### ISSUE THREAD

**Issue by darkphalanx** [gazpachoking/trainaspower#26]
Hi I get an issue when fetching the next workout:
Im in a taper fase in TAO maybe that has to do with it...

`2022-04-20 18:16:27.773 | INFO     | trainaspower.trainasone:get_next_workouts:41 - Fetching next TrainAsOne workout.
2022-04-20 18:16:28.774 | DEBUG    | __main__:main:100 - Error
Traceback (most recent call last):

  File "trainaspower\trainasone.py", line 98, in get_workout

AttributeError: 'NoneType' object has no attribute 'group'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "trainaspower\trainasone.py", line 51, in get_next_workouts

  File "trainaspower\trainasone.py", line 108, in get_workout

trainaspower.trainasone.FindWorkoutException: Error finding workout steps: ("'NoneType' object has no attribute 'group'",)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "trainaspower\main.py", line 108, in <module>

> File "trainaspower\main.py", line 88, in main

  File "trainaspower\trainasone.py", line 56, in get_next_workouts

trainaspower.trainasone.FindWorkoutException: Error finding next TaO workout: Error finding workout steps: ("'NoneType' object has no attribute 'group'",)
2022-04-20 18:16:28.776 | ERROR    | __main__:main:101 - Could not load next Train as One workout. Created taocalendar.html for debugging.
`

**Comment by jahofmann** [comment]
Can you upload your trainaspower.log?

**Comment by darkphalanx** [comment]
[trainaspower.log](https://github.com/gazpachoking/trainaspower/files/8523329/trainaspower.log)

Here you go :)

**Comment by jahofmann** [comment]
Ah, so no additional information. Can you download the Garmin Workout JSON from TAO and upload that?

**Comment by darkphalanx** [comment]
[workout-199X_8-economy.garminTraining.txt](https://github.com/gazpachoking/trainaspower/files/8523351/workout-199X_8-economy.garminTraining.txt)
Yes!

**Comment by jahofmann** [comment]
Wonderful, thank you. That file looks alright, I'll see if I can find out what's going wrong.

**Comment by jahofmann** [comment]
Are you on the latest release?

**Comment by darkphalanx** [comment]
Just came back from my run and it just downloaded the run for tomorrow correctly. Maybe todays run was "special", I don't know but now it works fine.

**Comment by gazpachoking** [comment]
I think everything is different now, let's make a new ticket if there is still an issue.
